import React from "react";
import { Provider } from "@/context/provider";
import "./globals.css";
import Headers from "@/components/globals/Headers";
import { ThemeProvider } from "@/context/theme-provider";
import { Prompt } from "next/font/google";
import Usernavbar from "@/components/profile/Usernavbar";
import AdminaNavbar from "@/components/profile/AdminNavber";
import { Toaster } from "@/components/ui/toaster";
import NextToploader from "nextjs-toploader";
import { auth } from "@/auth";

export const metadata = {
  title: "STDACTIVITYCHECK",
  description: "Generated by ohm",
};

const mainfont = Prompt({
  weight: "400",
  subsets: ["thai"],
  style: "normal",
  display: "swap",
  variable: "--font-main-font",
});

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await auth();
  const role = session?.user?.role || "";

  return (
    <html
      lang="th"
      className={`${mainfont.variable} !scroll-smooth font-myfont scrollbar-thin scrollbar-track-gray-100 scrollbar-thumb-amber-500 scrollbar-thumb-rounded`}
      suppressHydrationWarning={true}
    >
      <body>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <Provider>
            <NextToploader />
            <header>
              <Headers />
            </header>
            <div className="flex min-h-screen">
              {role === "admin" && <AdminaNavbar />}
              {role === "user" && <Usernavbar />}
              <main className="flex-1 overflow-hidden max-md:pb-14 sm:px-6">
                {children}
              </main>
            </div>
            <Toaster />
          </Provider>
        </ThemeProvider>
      </body>
    </html>
  );
}
