import React from "react";
import { Provider } from "@/context/provider";
import "./globals.css";
import Headers from "@/components/globals/Headers";

import { Prompt } from "next/font/google";
import Usernavbar from "@/components/profile/Usernavbar";
import { getServerSession } from "next-auth";
import { authOptions } from "./api/auth/[...nextauth]/route";
import AdminaNavbar from "@/components/profile/AdminNavber";

export const metadata = {
  title: "STDACTIVITYCHECK",
  description: "Generated by ohm",
};

// If loading a variable font, you don't need to specify the font weight
const mainfont = Prompt({
  weight: "400",
  subsets: ["thai"],
  style: "normal",
  display: "swap",
  variable: "--font-main-font",
});

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession(authOptions);
  const role = session?.user?.role;
  return (
    <html
      lang="th"
      className={`${mainfont.variable}  !scroll-smooth font-myfont scrollbar-thin scrollbar-track-gray-100 scrollbar-thumb-amber-500 scrollbar-thumb-rounded `}
      suppressHydrationWarning={true}
    >
      <body>
        <Provider>
          <header>
            <Headers />
          </header>

          <div className="flex">
            {role === "admin" ? (
              <>
                <AdminaNavbar />
              </>
            ) : role === "user" ? (
              <>
                <Usernavbar />
              </>
            ) : null}
            <section>
              <div>{children}</div>
            </section>
          </div>
        </Provider>
      </body>
    </html>
  );
}
