import { Provider } from "@/context/provider";
import "./globals.css";
import Headers from "@/components/globals/Headers";

import { Prompt } from "next/font/google";
import Usernavbar from "@/components/profile/Usernavbar";
import { getServerSession } from 'next-auth'
import { authOptions } from "./api/auth/[...nextauth]/route";
import AdminaNavbar from "@/components/profile/AdminNavber";
import Head from "next/head"

export const metadata = {
  title: "STDACTIVITYCHECK",
  description: "Generated by ohm",
};

// If loading a variable font, you don't need to specify the font weight
const mainfont = Prompt({
  weight: "400",
  subsets: ["thai"],
  style:"normal",
  display: "swap",
  variable: "--font-main-font",
});
export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession(authOptions);
  const role = session?.user?.role;
  return (
    <html
      lang="th"
      className={`${mainfont.variable}  font-myfont !scroll-smooth scrollbar-thin scrollbar-thumb-rounded scrollbar-thumb-amber-500 scrollbar-track-gray-100 `}
      suppressHydrationWarning={true}
     
    >
    

     
    
        
      <body className={`bg-[#fcfcfc]`}>
      <Provider>
        <header>
        <Headers />
        </header>
        
         
         
          <div className='flex flex-auto'>
          {role === 'admin' ? (
          <>
         
          <AdminaNavbar/>
           
          </>
        ) : role === 'user' ? (
          <>
             <Usernavbar/>
           
          </>
        ) : null}
      
    
          {children}
         
        </div>
        </Provider>
        </body>
  
      
    </html>
  );
}
